require 'raingrams/openvocabulary/unigrammodel'
require 'raingrams/openvocabulary/multigrammodel'
require 'raingrams/openvocabulary/bigrammodel'
require 'raingrams/openvocabulary/trigrammodel'
require 'raingrams/openvocabulary/quadgrammodel'
require 'raingrams/openvocabulary/pentagrammodel'
require 'raingrams/openvocabulary/hexagrammodel'
