require 'raingrams/openvocabulary/unigram_model'
require 'raingrams/openvocabulary/multigram_model'
require 'raingrams/openvocabulary/bigram_model'
require 'raingrams/openvocabulary/trigram_model'
require 'raingrams/openvocabulary/quadgram_model'
require 'raingrams/openvocabulary/pentagram_model'
require 'raingrams/openvocabulary/hexagram_model'
